### ISSUE TITLE
[BUG] 배포 주소로 요청 시 mixed content 에러 발생

### ISSUE THREAD

**Issue by sojinjang** [sojinjang/podo-log#180]
### 🤷 Describe the bug
프론트 배포 주소 -> 백엔드 배포 주소로 요청 시 https -> http 요청 블락 에러 발생

### 📸 Screenshots
![image](https://user-images.githubusercontent.com/111125577/220231253-bb94a1c9-5dc2-4010-b983-4d4641a843ee.png)

### 💬 Additional context 
시도해본 것: 요청헤더에 아래 코드 포함시키기
```typescript
<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
```
-> 여전히 통신 되지않음.
<img width="805" alt="image" src="https://user-images.githubusercontent.com/111125577/220231848-24c44f53-32aa-4196-90cd-45beffbcadd9.png">

**Comment by ahosang** [comment]
서버를 https 로 전환
1. 도메인 구매
2. AWS Certificate Manager 에서 ssl 인증 받음
3. ELB 를 통한 https 적용
