### ISSUE TITLE
[BUG] bookId를 날렸는데도 bookId is required 에러 발생

### ISSUE THREAD

**Issue by sojinjang** [sojinjang/podo-log#78]
### 🤷 Describe the bug
bookId 보냈는데도 `bookId is required` 에러 발생

### 🐒 To Reproduce
1. form data에 number type을 추가할 수 없어서 string으로 bookId 넣음.
2. api 문서에는 bookId type이 number로 되어있는 상태.

### 📸 Screenshots
<img width="600" alt="image" src="https://user-images.githubusercontent.com/111125577/216691999-f4c87004-8fba-48bb-804e-7c2a7e181ec3.png">
<img width="600" alt="image" src="https://user-images.githubusercontent.com/111125577/216692031-9f55a0f3-44b6-44eb-ac7e-21e49b37fc9f.png">
<img width="400" alt="image" src="https://user-images.githubusercontent.com/111125577/216692058-068246d4-ba10-4f42-8cde-b9c24ad5685d.png">

### 💬 Additional context
`bookId is required`라는 에러 메시지가 data type이 달라서 발생한 에러인지 백단 코드에서 schema 확인 필요. 
number type으로 validate중이라면 백에서 string 타입으로 받아서 number로 변환해 써야 할 것으로 보임. [참고 링크 📎](https://stackoverflow.com/questions/33870800/send-integers-in-formdata)

**Comment by ahosang** [comment]
entype 을 multipart/formdata 로 보낼때는 express 의 request.body 가 비어서 온다. 
이때 multer 를 사용하면 form-data를 파싱해서 text 타입의 경우 req.body에 넣어주고 그외 타입의 경우 req.files(한 개이면 req.file)에 넣어준다. 
따라서 multer 미들웨어를 먼저 거치게 하였다.
